[package]
name = "sozlukdb"
version = "0.1.0"
edition = "2021"
#![feature(type_ascription)]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.2"

